export default {
	// 渔船一般性隐患排查登记表
	// 救生设备
	// 救生筏
	'lifeRaft': '按规定配齐,救生筏上不能堆放网具等杂物，不能用线索捆扎，包装带是否剪掉',
	// 救生圈
	'ringBuoyFirst': '1.船舶名称和船籍港清楚',
	'ringBuoySecond': '2.正确安装在救生圈支架上',
	'ringBuoyThird': '3.外观不能破损及老化，配备反光带',
	'ringBuoyFourth': '4.配备1个有效期内的自亮浮灯,配备救生浮索（船长大于24米需配备2根,小于24米配1根',
	'ringBuoyFifth': '5.数量按船检证书要求配备',
	// 救生衣
	'lifeJackFirst': '1.数量按照船检证书配齐，工作救生衣数量按照实际人数配备',
	'lifeJackSecond': '2.救生衣存放处张贴存放标志，敦生衣标记船舶名称和船籍港',
	'lifeJackThird': '3.配备救生衣灯、哨笛、提环、伴带',
	'lifeJackFourth': '4.外观不能破损及老化，配备反光带',
	// 其他救生设备
	'otherPreserverFirst': '1.24米以上渔船通用报警系统安装到位并有效',
	'otherPreserverSecond': '2.救生软梯放置在显著位置，急用可取',
	'otherPreserverThird': '3.按船拾证书配备有效期内的烟火信号弹',
	// 消防设备
	// 灭火器
	'extinguisherFirst': '1.数量按船检证书要求配备',
	'extinguisherSecond': '2.灭火器应在有效期内',
	'extinguisherThird': '3.用固定架安装在机舱、厨房、驾驶窒等处所',
	// 水消防
	'waterFireFightingFirst': '消火栓和消防箱要完好，水龙带按扣完好，水枪应为水雾两用型',
	// 信号设备
	// 航行基本号灯
	'signalLamp': '航行灯和作业灯要正确安装且有效',
	// 号型
	'signalLampType': '黑色锚球和双圆锥体各1个',
	// 号笛、号钟
	'signalLampStatus': '号钟要按规定安装，号笛可正常使用',
	// 通导设备
	// 通信设备
	'communicationEquipment': '中高频、甚高频、双向艇筏甚高频无线电话等要正确安装并能有效使用',
	// 导航设备
	'navigationalAids': '北斗、雷达应答器、应急无线电示位标等要正确安装并能有效使用',
	// 其他情况
	// 逃生通道
	'escapeTrunk': '船员室、驾驶室逃生通道畅通',
	// 鱼舱
	'fishHold': '鱼舱清洗干净，无污水',
	// 电线线路
	'wire': '电线外层不能破损裸露',
	// 液化气瓶
	'liquefiedBottle': '液化气瓶要关闭',
	// “五超”行为
	'behavior': '不能有超载、超高、超员、超风力、超航区航行作业行为',
	// 规章锢度
	'regulation': '落实编组生产、值班了望等制度',
	
	// 渔船专业性隐患排查登记表
	// 四种机器
	// 主机、辅机、舵机、锚机
	'machine': '主机、辅机、舵机、锚机正常运转',
	// 救生筏
	'lifeRaft1': '静水压力释放器要有效并正确安装',
	// 其他救生设备
	'otherPreserverFirst1': '1.24米以上渔船通用报警系统安装到位并有效',
	'otherPreserverSecond1': '2.水位报警器要有效',
	// 警报设备
	// 氮泄漏监控报警系统
	'alarmFirst': '正常有效',
	// 弃船蓍报设备
	'alarmSecond': '正常有效',
	// 信号设备
	// 航行基本号灯
	'signalLamp1': '航行灯和作业灯要正确安装且有效',
	// 号型
	'signalLampType1': '黑色锚球和双圆锥体各1个',
	// 号笛、号钟
	'signalLampStatus1': '号钟要按规定安装，号笛可正常使用',
	// 消防、防火情况
	// 水消防
	'waterFireFightingFirst1': '1.消火栓和消防箱要完好,水龙带接扣完好,水枪应为水雾两用型',
	'waterFireFightingSecond': '2.消防水管不能用软管连接，不得用塑料管替代',
	// 厨房防火
	'kitchenFirst': '1.拆除可燃材料',
	'kitchenSecond': '2.安装经认可的防火门',
	'kitchenThird': '3.煤气瓶要放在敞开式的舱内，瓶与灶具连接管线完好',
	// 机舱防火
	'engineRoomFirst': '1.安装经认可的防火门',
	'engineRoomSecond': '2.机舱内不得有木板、有开口，地板和楼梯不得用木质板',
	'engineRoomThird': '3.主机排气管应做防火隔热包扎',
	'engineRoomFourth': '4.舱底无污油',
	// 电气设备防火
	'electricAccessoryFirst': '1.线路老化、外层破损裸露的情况要及时更换',
	'electricAccessorySecond': '2.配电箱要完好,要用船用电缆,严禁私拉乱接',
	// 其他情况
	// 渔捞起重设备
	'fishingEquipmentFirst': '吊杆钢丝要完好，插销、滑轮、吊钩无磨损',
	'fishingEquipmentSecond': '卷扬机运转正常，转盘正常',
	// 船体结构
	'hullFirst': '1.风雨密门、窗、盖必须完好',
	'hullSecond': '2.排水舷口的数量和面积要足够',
	'hullThird': '3.正确勘划水尺和载重线标志',
	// 海底阀
	'submarineValve': '海底阀性能完好',
	// 渔获物储藏室
	'catchStorageRoom': '渔获物储藏室排风畅通',
	// 机舱
	'engineRoom': '机舱油气废气及时排出',
}